spring:
  application:
    name: coupon
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/coupon}
    username: ${SPRING_DATASOURCE_USERNAME:coupon}
    password: ${SPRING_DATASOURCE_PASSWORD:coupon}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  mvc:
    problemdetails:
      enabled: true

  logging:
    level:
      com.coen.coupon: INFO
      org.hibernate.SQL: WARN
      org.hibernate.orm.jdbc.bind: WARN
